# add homebrewed stuff to path
PATH=$PATH:/opt/homebrew/bin

# vi keybindings
bindkey -v

# aliases

# git command for dotfiles in $HOME
alias codium=code

if ! pgrep -f "crond" >/dev/null; then
echo "[Starting crond...]" && crond && echo "[OK]"
else
echo "[crond is running]"
fi
